In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9])
print (a)

[1 2 3 4 5 6 7 8 9]


In [4]:
print (type(a))

<class 'numpy.ndarray'>


In [5]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)])
print (b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
c=np.arange(0,100)
print (c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [8]:
d=np.linspace(0,50,10)
print (d)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [13]:
e=np.loadtxt("first.txt",delimiter=",")
print (e)

[1. 2. 3. 4. 5. 6. 6. 7. 7.]


In [14]:
f=np.empty((3,3))
print (f)

[[1. 2. 3.]
 [4. 5. 6.]
 [6. 7. 7.]]


In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Functions

In [16]:
a=np.array([1,2,3,4,5,6,7],np.int8)
print (a)

[1 2 3 4 5 6 7]


In [17]:
a.dtype

dtype('int8')

In [18]:
a.shape

(7,)

In [19]:
a.ndim

1

In [20]:
a.size

7

In [21]:
a.nbytes

7

In [23]:
a.argmax()

6

In [24]:
a.argmin()

0

In [25]:
a.argsort()

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [26]:
n=np.zeros([10,10])
print (n)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [28]:
n=np.ones([10,10])
print (n)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
n.dtype

dtype('float64')

In [34]:
n=np.arange(99)
print (n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [44]:
n.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [45]:
n.shape

(99,)

In [46]:
np.sum(n)

4851

In [47]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)])
print (b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
np.sum (b,axis=0)

array([12, 15, 18])

In [51]:
a=np.array([1,2,3,4,5,6,7],np.int8)
print (a)

[1 2 3 4 5 6 7]


In [52]:
b=a+2
print (b)

[3 4 5 6 7 8 9]


In [54]:
b==a

array([ True,  True,  True,  True,  True,  True,  True])

In [55]:
b.T

array([3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [56]:
a.T

array([1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [58]:
b.T

array([3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [ ]:
np.cross()